package evmop

const (
	code_STOP           = byte(0x00)
	code_ADD            = byte(0x01)
	code_MUL            = byte(0x02)
	code_SUB            = byte(0x03)
	code_DIV            = byte(0x04)
	code_SDIV           = byte(0x05)
	code_MOD            = byte(0x06)
	code_SMOD           = byte(0x07)
	code_ADDMOD         = byte(0x08)
	code_MULMOD         = byte(0x09)
	code_EXP            = byte(0x0a)
	code_SIGNEXTEND     = byte(0x0b)

	code_LT             = byte(0x10)
	code_GT             = byte(0x11)
	code_SLT            = byte(0x12)
	code_SGT            = byte(0x13)
	code_EQ             = byte(0x14)
	code_ISZERO         = byte(0x15)
	code_AND            = byte(0x16)
	code_OR             = byte(0x17)
	code_XOR            = byte(0x18)
	code_NOT            = byte(0x19)
	code_BYTE           = byte(0x1a)

	code_SHA3           = byte(0x20)
	code_ADDRESS        = byte(0x30)
	code_BALANCE        = byte(0x31)
	code_ORIGIN         = byte(0x32)
	code_CALLER         = byte(0x33)
	code_CALLVALUE      = byte(0x34)
	code_CALLDATALOAD   = byte(0x35)
	code_CALLDATASIZE   = byte(0x36)
	code_CALLDATACOPY   = byte(0x37)
	code_CODESIZE       = byte(0x38)
	code_CODECOPY       = byte(0x39)
	code_GASPRICE       = byte(0x3a)
	code_EXTCODESIZE    = byte(0x3b)
	code_EXTCODECOPY    = byte(0x3c)
	code_RETURNDATASIZE = byte(0x3d)
	code_RETURNDATACOPY = byte(0x3e)

	code_BLOCKHASH      = byte(0x40)
	code_COINBASE       = byte(0x41)
	code_TIMESTAMP      = byte(0x42)
	code_NUMBER         = byte(0x43)
	code_DIFFICULTY     = byte(0x44)
	code_GASLIMIT       = byte(0x45)

	code_POP            = byte(0x50)
	code_MLOAD          = byte(0x51)
	code_MSTORE         = byte(0x52)
	code_MSTORE8        = byte(0x53)
	code_SLOAD          = byte(0x54)
	code_SSTORE         = byte(0x55)
	code_JUMP           = byte(0x56)
	code_JUMPI          = byte(0x57)
	code_PC             = byte(0x58)
	code_MSIZE          = byte(0x59)
	code_GAS            = byte(0x5a)
	code_JUMPDEST       = byte(0x5b)

	code_LOG0           = byte(0xa0)
	code_LOG1           = byte(0xa1)
	code_LOG2           = byte(0xa2)
	code_LOG3           = byte(0xa3)
	code_LOG4           = byte(0xa4)

	code_CREATE         = byte(0xf0)
	code_CALL           = byte(0xf1)
	code_CALLCODE       = byte(0xf2)
	code_RETURN         = byte(0xf3)
	code_DELEGATECALL   = byte(0xf4)
	code_CALLBLACKBOX   = byte(0xf5)

	code_STATICCALL     = byte(0xfa)

	code_REVERT         = byte(0xfd)

	code_SUICIDE        = byte(0xff)
)
